---
version: 2.1

#orbs:
#  hello: sunakan/hello-world@0.0.2

jobs:
  myjob:
    docker:
      - image: "circleci/node:dubnium-stretch"
    steps:
      - echo-hello:
        to: "こんにちは世界"


commands:
  echo-hello:
    description: "CircleCIの結果に出力"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
