# Authoring Reusable Commands

version: 2.1

commands:
  sayhello:
    description: "CIでもHelloWorldサンプルがあるなんて!!"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
