version: 2
jobs:
  build:
    docker:
    - image: circleci/node:dubnium-stretch
    steps:
    - run:
        name: echoするだけ
        command: echo こんにちは世界
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# ---
# version: 2.1
# 
# jobs:
#   build:
#     docker:
#       - image: \"circleci/node:dubnium-stretch\"
#     steps:
#       - echo-hello:
#           to: \"\u3053\u3093\u306B\u3061\u306F\u4E16\u754C\"
# 
# commands:
#   echo-hello:
#     description: \"CircleCI\u306E\u7D50\u679C\u306B\u51FA\u529B\"
#     parameters:
#       to:
#         type: string
#         default: \"Hello World\"
#     steps:
#       - run:
#           name: \"echo\u3059\u308B\u3060\u3051\"
#           command: echo << parameters.to >>